version: '3'
networks:
  td.net:
    driver: bridge
services:

  td:
    image: 'canals/php:latest'
    env_file: ./.env
    ports:
      - '8000:80'
      - '1443'
    volumes:
      - ./hellokant/public:/var/www/html
      - ./hellokant:/var/www
    working_dir: /var/www/
    networks:
      td.net:
        aliases:
          - td.local
    depends_on:
      - td.article.db

  # service sql pour le stockage des commandes -
  # utilisé par l'api order
  td.article.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./article.env
    ports:
      - '18252:80'
    networks:
      - td.net
    volumes:
      - ./hellokant/sql:/var/sql


  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - td.net